module.exports = {
	name: "Kommuneinndeling 2014",
	validFrom: "2014-01-01",
	validTo: "+999999999-12-31",
	introduction:
		"Kommuneinndelingen er en administrativ inndeling av Norge. Kommunen er betegnelsen både på en politisk og forvaltningsmessig nivå og betegnelsen på et regionalt nivå i statistikken.\n\nI medhold av kommuneloven §3 nr. 3 ble det den 7. mars 2014 vedtatt trespråklig kommunenavn Omasvuotna Storfjord Omasvuonon (samisk norsk kvensk) på 1939 Storfjord kommune og den 13. juni 2014 vedtatt tospråklig kommunenavn Raarvihke Røyrvik (samisk norsk) på 1739 Røyrvik kommune.",
	contactPerson: {
		name: "Hartvedt, Henning",
		email: "Henning.Hartvedt@ssb.no",
		phone: "62885265",
	},
	owningSection: "320",
	legalBase: "",
	publications:
		"http://www.ssb.no/emner/00/90/rapp_9913/ \nhttp://www.ssb.no/emner/00/00/20/nos_c513/\nhttp://www.ssb.no/vis/kommuner/dokumentasjon.html",
	derivedFrom: "",
	published: ["Bokmål", "Nynorsk", "Engelsk"],
	correspondenceTables: [
		{
			name: "Kommuneinndeling 2014 - Delområde- og grunnkretsinndeling 2014",
			contactPerson: {
				name: "Hartvedt, Henning",
				email: "Henning.Hartvedt@ssb.no",
				phone: "62885265",
			},
			owningSection: "320",
			source: "Kommuneinndeling 2014",
			target: "Delområde- og grunnkretsinndeling 2014",
			changeTable: false,
			_links: {
				self: {
					href: "/correspondencetables/128",
				},
			},
		},
		{
			name: "Kommuneinndeling 2014 - Bydelsinndeling 2004",
			contactPerson: {
				name: "Hartvedt, Henning",
				email: "Henning.Hartvedt@ssb.no",
				phone: "62885265",
			},
			owningSection: "320",
			source: "Kommuneinndeling 2014",
			target: "Bydelsinndeling 2004",
			changeTable: false,
			_links: {
				self: {
					href: "/correspondencetables/129",
				},
			},
		},
		{
			name: "Kommuneinndeling 2014 - Kommuneinndeling 2013",
			contactPerson: {
				name: "Hartvedt, Henning",
				email: "Henning.Hartvedt@ssb.no",
				phone: "62885265",
			},
			owningSection: "320",
			source: "Kommuneinndeling 2014",
			target: "Kommuneinndeling 2013",
			changeTable: true,
			_links: {
				self: {
					href: "/correspondencetables/130",
				},
			},
		},
		{
			name: "Kommuneinndeling 2014 - Delområde- og grunnkretsinndeling 2014",
			contactPerson: {
				name: "Hartvedt, Henning",
				email: "Henning.Hartvedt@ssb.no",
				phone: "62885265",
			},
			owningSection: "320",
			source: "Kommuneinndeling 2014",
			target: "Delområde- og grunnkretsinndeling 2014",
			changeTable: false,
			_links: {
				self: {
					href: "/correspondencetables/131",
				},
			},
		},
		{
			name: "Kommuneinndeling 2014 - Delområde- og grunnkretsinndeling 2016",
			contactPerson: {
				name: "Hartvedt, Henning",
				email: "Henning.Hartvedt@ssb.no",
				phone: "62885265",
			},
			owningSection: "320",
			source: "Kommuneinndeling 2014",
			target: "Delområde- og grunnkretsinndeling 2016",
			changeTable: false,
			_links: {
				self: {
					href: "/correspondencetables/145",
				},
			},
		},
	],
	classificationVariants: [
		{
			name: "kommunestørrelse",
			_links: {
				self: {
					href: "/variants/956",
				},
			},
		},
	],
	changelogs: [
		{
			changeOccured: "2016-06-30T11:58:47.000+0000",
			description: "Ingen faktisk endring",
		},
		{
			changeOccured: "2016-07-08T11:17:07.000+0000",
			description: "korrigering",
		},
	],
	levels: [
		{
			levelNumber: 1,
			levelName: "Kommune",
		},
	],
	classificationItems: [
		{
			code: "0101",
			level: "1",
			name: "Halden",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0104",
			level: "1",
			name: "Moss",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0105",
			level: "1",
			name: "Sarpsborg",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0106",
			level: "1",
			name: "Fredrikstad",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0111",
			level: "1",
			name: "Hvaler",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0118",
			level: "1",
			name: "Aremark",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0119",
			level: "1",
			name: "Marker",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0121",
			level: "1",
			name: "Rømskog",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0122",
			level: "1",
			name: "Trøgstad",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0123",
			level: "1",
			name: "Spydeberg",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0124",
			level: "1",
			name: "Askim",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0125",
			level: "1",
			name: "Eidsberg",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0127",
			level: "1",
			name: "Skiptvet",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0128",
			level: "1",
			name: "Rakkestad",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0135",
			level: "1",
			name: "Råde",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0136",
			level: "1",
			name: "Rygge",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0137",
			level: "1",
			name: "Våler",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0138",
			level: "1",
			name: "Hobøl",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0211",
			level: "1",
			name: "Vestby",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0213",
			level: "1",
			name: "Ski",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0214",
			level: "1",
			name: "Ås",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0215",
			level: "1",
			name: "Frogn",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0216",
			level: "1",
			name: "Nesodden",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0217",
			level: "1",
			name: "Oppegård",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0219",
			level: "1",
			name: "Bærum",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0220",
			level: "1",
			name: "Asker",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0221",
			level: "1",
			name: "Aurskog-Høland",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0226",
			level: "1",
			name: "Sørum",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0227",
			level: "1",
			name: "Fet",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0228",
			level: "1",
			name: "Rælingen",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0229",
			level: "1",
			name: "Enebakk",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0230",
			level: "1",
			name: "Lørenskog",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0231",
			level: "1",
			name: "Skedsmo",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0233",
			level: "1",
			name: "Nittedal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0234",
			level: "1",
			name: "Gjerdrum",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0235",
			level: "1",
			name: "Ullensaker",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0236",
			level: "1",
			name: "Nes",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0237",
			level: "1",
			name: "Eidsvoll",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0238",
			level: "1",
			name: "Nannestad",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0239",
			level: "1",
			name: "Hurdal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0301",
			level: "1",
			name: "Oslo",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0402",
			level: "1",
			name: "Kongsvinger",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0403",
			level: "1",
			name: "Hamar",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0412",
			level: "1",
			name: "Ringsaker",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0415",
			level: "1",
			name: "Løten",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0417",
			level: "1",
			name: "Stange",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0418",
			level: "1",
			name: "Nord-Odal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0419",
			level: "1",
			name: "Sør-Odal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0420",
			level: "1",
			name: "Eidskog",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0423",
			level: "1",
			name: "Grue",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0425",
			level: "1",
			name: "Åsnes",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0426",
			level: "1",
			name: "Våler",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0427",
			level: "1",
			name: "Elverum",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0428",
			level: "1",
			name: "Trysil",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0429",
			level: "1",
			name: "Åmot",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0430",
			level: "1",
			name: "Stor-Elvdal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0432",
			level: "1",
			name: "Rendalen",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0434",
			level: "1",
			name: "Engerdal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0436",
			level: "1",
			name: "Tolga",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0437",
			level: "1",
			name: "Tynset",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0438",
			level: "1",
			name: "Alvdal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0439",
			level: "1",
			name: "Folldal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0441",
			level: "1",
			name: "Os",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0501",
			level: "1",
			name: "Lillehammer",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0502",
			level: "1",
			name: "Gjøvik",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0511",
			level: "1",
			name: "Dovre",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0512",
			level: "1",
			name: "Lesja",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0513",
			level: "1",
			name: "Skjåk",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0514",
			level: "1",
			name: "Lom",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0515",
			level: "1",
			name: "Vågå",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0516",
			level: "1",
			name: "Nord-Fron",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0517",
			level: "1",
			name: "Sel",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0519",
			level: "1",
			name: "Sør-Fron",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0520",
			level: "1",
			name: "Ringebu",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0521",
			level: "1",
			name: "Øyer",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0522",
			level: "1",
			name: "Gausdal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0528",
			level: "1",
			name: "Østre Toten",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0529",
			level: "1",
			name: "Vestre Toten",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0532",
			level: "1",
			name: "Jevnaker",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0533",
			level: "1",
			name: "Lunner",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0534",
			level: "1",
			name: "Gran",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0536",
			level: "1",
			name: "Søndre Land",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0538",
			level: "1",
			name: "Nordre Land",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0540",
			level: "1",
			name: "Sør-Aurdal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0541",
			level: "1",
			name: "Etnedal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0542",
			level: "1",
			name: "Nord-Aurdal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0543",
			level: "1",
			name: "Vestre Slidre",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0544",
			level: "1",
			name: "Øystre Slidre",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0545",
			level: "1",
			name: "Vang",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0602",
			level: "1",
			name: "Drammen",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0604",
			level: "1",
			name: "Kongsberg",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0605",
			level: "1",
			name: "Ringerike",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0612",
			level: "1",
			name: "Hole",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0615",
			level: "1",
			name: "Flå",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0616",
			level: "1",
			name: "Nes",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0617",
			level: "1",
			name: "Gol",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0618",
			level: "1",
			name: "Hemsedal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0619",
			level: "1",
			name: "Ål",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0620",
			level: "1",
			name: "Hol",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0621",
			level: "1",
			name: "Sigdal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0622",
			level: "1",
			name: "Krødsherad",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0623",
			level: "1",
			name: "Modum",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0624",
			level: "1",
			name: "Øvre Eiker",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0625",
			level: "1",
			name: "Nedre Eiker",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0626",
			level: "1",
			name: "Lier",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0627",
			level: "1",
			name: "Røyken",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0628",
			level: "1",
			name: "Hurum",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0631",
			level: "1",
			name: "Flesberg",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0632",
			level: "1",
			name: "Rollag",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0633",
			level: "1",
			name: "Nore og Uvdal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0701",
			level: "1",
			name: "Horten",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0702",
			level: "1",
			name: "Holmestrand",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0704",
			level: "1",
			name: "Tønsberg",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0706",
			level: "1",
			name: "Sandefjord",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0709",
			level: "1",
			name: "Larvik",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0711",
			level: "1",
			name: "Svelvik",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0713",
			level: "1",
			name: "Sande",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0714",
			level: "1",
			name: "Hof",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0716",
			level: "1",
			name: "Re",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0719",
			level: "1",
			name: "Andebu",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0720",
			level: "1",
			name: "Stokke",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0722",
			level: "1",
			name: "Nøtterøy",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0723",
			level: "1",
			name: "Tjøme",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0728",
			level: "1",
			name: "Lardal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0805",
			level: "1",
			name: "Porsgrunn",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0806",
			level: "1",
			name: "Skien",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0807",
			level: "1",
			name: "Notodden",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0811",
			level: "1",
			name: "Siljan",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0814",
			level: "1",
			name: "Bamble",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0815",
			level: "1",
			name: "Kragerø",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0817",
			level: "1",
			name: "Drangedal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0819",
			level: "1",
			name: "Nome",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0821",
			level: "1",
			name: "Bø",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0822",
			level: "1",
			name: "Sauherad",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0826",
			level: "1",
			name: "Tinn",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0827",
			level: "1",
			name: "Hjartdal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0828",
			level: "1",
			name: "Seljord",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0829",
			level: "1",
			name: "Kviteseid",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0830",
			level: "1",
			name: "Nissedal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0831",
			level: "1",
			name: "Fyresdal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0833",
			level: "1",
			name: "Tokke",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0834",
			level: "1",
			name: "Vinje",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0901",
			level: "1",
			name: "Risør",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0904",
			level: "1",
			name: "Grimstad",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0906",
			level: "1",
			name: "Arendal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0911",
			level: "1",
			name: "Gjerstad",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0912",
			level: "1",
			name: "Vegårshei",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0914",
			level: "1",
			name: "Tvedestrand",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0919",
			level: "1",
			name: "Froland",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0926",
			level: "1",
			name: "Lillesand",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0928",
			level: "1",
			name: "Birkenes",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0929",
			level: "1",
			name: "Åmli",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0935",
			level: "1",
			name: "Iveland",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0937",
			level: "1",
			name: "Evje og Hornnes",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0938",
			level: "1",
			name: "Bygland",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0940",
			level: "1",
			name: "Valle",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "0941",
			level: "1",
			name: "Bykle",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1001",
			level: "1",
			name: "Kristiansand",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1002",
			level: "1",
			name: "Mandal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1003",
			level: "1",
			name: "Farsund",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1004",
			level: "1",
			name: "Flekkefjord",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1014",
			level: "1",
			name: "Vennesla",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1017",
			level: "1",
			name: "Songdalen",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1018",
			level: "1",
			name: "Søgne",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1021",
			level: "1",
			name: "Marnardal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1026",
			level: "1",
			name: "Åseral",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1027",
			level: "1",
			name: "Audnedal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1029",
			level: "1",
			name: "Lindesnes",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1032",
			level: "1",
			name: "Lyngdal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1034",
			level: "1",
			name: "Hægebostad",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1037",
			level: "1",
			name: "Kvinesdal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1046",
			level: "1",
			name: "Sirdal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1101",
			level: "1",
			name: "Eigersund",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1102",
			level: "1",
			name: "Sandnes",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1103",
			level: "1",
			name: "Stavanger",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1106",
			level: "1",
			name: "Haugesund",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1111",
			level: "1",
			name: "Sokndal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1112",
			level: "1",
			name: "Lund",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1114",
			level: "1",
			name: "Bjerkreim",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1119",
			level: "1",
			name: "Hå",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1120",
			level: "1",
			name: "Klepp",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1121",
			level: "1",
			name: "Time",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1122",
			level: "1",
			name: "Gjesdal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1124",
			level: "1",
			name: "Sola",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1127",
			level: "1",
			name: "Randaberg",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1129",
			level: "1",
			name: "Forsand",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1130",
			level: "1",
			name: "Strand",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1133",
			level: "1",
			name: "Hjelmeland",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1134",
			level: "1",
			name: "Suldal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1135",
			level: "1",
			name: "Sauda",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1141",
			level: "1",
			name: "Finnøy",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1142",
			level: "1",
			name: "Rennesøy",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1144",
			level: "1",
			name: "Kvitsøy",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1145",
			level: "1",
			name: "Bokn",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1146",
			level: "1",
			name: "Tysvær",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1149",
			level: "1",
			name: "Karmøy",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1151",
			level: "1",
			name: "Utsira",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1160",
			level: "1",
			name: "Vindafjord",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1201",
			level: "1",
			name: "Bergen",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1211",
			level: "1",
			name: "Etne",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1216",
			level: "1",
			name: "Sveio",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1219",
			level: "1",
			name: "Bømlo",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1221",
			level: "1",
			name: "Stord",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1222",
			level: "1",
			name: "Fitjar",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1223",
			level: "1",
			name: "Tysnes",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1224",
			level: "1",
			name: "Kvinnherad",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1227",
			level: "1",
			name: "Jondal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1228",
			level: "1",
			name: "Odda",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1231",
			level: "1",
			name: "Ullensvang",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1232",
			level: "1",
			name: "Eidfjord",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1233",
			level: "1",
			name: "Ulvik",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1234",
			level: "1",
			name: "Granvin",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1235",
			level: "1",
			name: "Voss",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1238",
			level: "1",
			name: "Kvam",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1241",
			level: "1",
			name: "Fusa",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1242",
			level: "1",
			name: "Samnanger",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1243",
			level: "1",
			name: "Os",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1244",
			level: "1",
			name: "Austevoll",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1245",
			level: "1",
			name: "Sund",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1246",
			level: "1",
			name: "Fjell",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1247",
			level: "1",
			name: "Askøy",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1251",
			level: "1",
			name: "Vaksdal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1252",
			level: "1",
			name: "Modalen",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1253",
			level: "1",
			name: "Osterøy",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1256",
			level: "1",
			name: "Meland",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1259",
			level: "1",
			name: "Øygarden",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1260",
			level: "1",
			name: "Radøy",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1263",
			level: "1",
			name: "Lindås",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1264",
			level: "1",
			name: "Austrheim",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1265",
			level: "1",
			name: "Fedje",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1266",
			level: "1",
			name: "Masfjorden",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1401",
			level: "1",
			name: "Flora",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1411",
			level: "1",
			name: "Gulen",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1412",
			level: "1",
			name: "Solund",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1413",
			level: "1",
			name: "Hyllestad",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1416",
			level: "1",
			name: "Høyanger",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1417",
			level: "1",
			name: "Vik",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1418",
			level: "1",
			name: "Balestrand",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1419",
			level: "1",
			name: "Leikanger",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1420",
			level: "1",
			name: "Sogndal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1421",
			level: "1",
			name: "Aurland",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1422",
			level: "1",
			name: "Lærdal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1424",
			level: "1",
			name: "Årdal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1426",
			level: "1",
			name: "Luster",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1428",
			level: "1",
			name: "Askvoll",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1429",
			level: "1",
			name: "Fjaler",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1430",
			level: "1",
			name: "Gaular",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1431",
			level: "1",
			name: "Jølster",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1432",
			level: "1",
			name: "Førde",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1433",
			level: "1",
			name: "Naustdal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1438",
			level: "1",
			name: "Bremanger",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1439",
			level: "1",
			name: "Vågsøy",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1441",
			level: "1",
			name: "Selje",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1443",
			level: "1",
			name: "Eid",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1444",
			level: "1",
			name: "Hornindal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1445",
			level: "1",
			name: "Gloppen",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1449",
			level: "1",
			name: "Stryn",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1502",
			level: "1",
			name: "Molde",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1504",
			level: "1",
			name: "Ålesund",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1505",
			level: "1",
			name: "Kristiansund",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1511",
			level: "1",
			name: "Vanylven",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1514",
			level: "1",
			name: "Sande",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1515",
			level: "1",
			name: "Herøy",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1516",
			level: "1",
			name: "Ulstein",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1517",
			level: "1",
			name: "Hareid",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1519",
			level: "1",
			name: "Volda",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1520",
			level: "1",
			name: "Ørsta",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1523",
			level: "1",
			name: "Ørskog",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1524",
			level: "1",
			name: "Norddal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1525",
			level: "1",
			name: "Stranda",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1526",
			level: "1",
			name: "Stordal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1528",
			level: "1",
			name: "Sykkylven",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1529",
			level: "1",
			name: "Skodje",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1531",
			level: "1",
			name: "Sula",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1532",
			level: "1",
			name: "Giske",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1534",
			level: "1",
			name: "Haram",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1535",
			level: "1",
			name: "Vestnes",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1539",
			level: "1",
			name: "Rauma",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1543",
			level: "1",
			name: "Nesset",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1545",
			level: "1",
			name: "Midsund",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1546",
			level: "1",
			name: "Sandøy",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1547",
			level: "1",
			name: "Aukra",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1548",
			level: "1",
			name: "Fræna",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1551",
			level: "1",
			name: "Eide",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1554",
			level: "1",
			name: "Averøy",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1557",
			level: "1",
			name: "Gjemnes",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1560",
			level: "1",
			name: "Tingvoll",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1563",
			level: "1",
			name: "Sunndal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1566",
			level: "1",
			name: "Surnadal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1567",
			level: "1",
			name: "Rindal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1571",
			level: "1",
			name: "Halsa",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1573",
			level: "1",
			name: "Smøla",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1576",
			level: "1",
			name: "Aure",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1601",
			level: "1",
			name: "Trondheim",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1612",
			level: "1",
			name: "Hemne",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1613",
			level: "1",
			name: "Snillfjord",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1617",
			level: "1",
			name: "Hitra",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1620",
			level: "1",
			name: "Frøya",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1621",
			level: "1",
			name: "Ørland",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1622",
			level: "1",
			name: "Agdenes",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1624",
			level: "1",
			name: "Rissa",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1627",
			level: "1",
			name: "Bjugn",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1630",
			level: "1",
			name: "Åfjord",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1632",
			level: "1",
			name: "Roan",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1633",
			level: "1",
			name: "Osen",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1634",
			level: "1",
			name: "Oppdal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1635",
			level: "1",
			name: "Rennebu",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1636",
			level: "1",
			name: "Meldal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1638",
			level: "1",
			name: "Orkdal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1640",
			level: "1",
			name: "Røros",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1644",
			level: "1",
			name: "Holtålen",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1648",
			level: "1",
			name: "Midtre Gauldal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1653",
			level: "1",
			name: "Melhus",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1657",
			level: "1",
			name: "Skaun",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1662",
			level: "1",
			name: "Klæbu",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1663",
			level: "1",
			name: "Malvik",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1664",
			level: "1",
			name: "Selbu",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1665",
			level: "1",
			name: "Tydal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1702",
			level: "1",
			name: "Steinkjer",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1703",
			level: "1",
			name: "Namsos",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1711",
			level: "1",
			name: "Meråker",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1714",
			level: "1",
			name: "Stjørdal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1717",
			level: "1",
			name: "Frosta",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1718",
			level: "1",
			name: "Leksvik",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1719",
			level: "1",
			name: "Levanger",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1721",
			level: "1",
			name: "Verdal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1724",
			level: "1",
			name: "Verran",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1725",
			level: "1",
			name: "Namdalseid",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1736",
			level: "1",
			name: "Snåase - Snåsa",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1738",
			level: "1",
			name: "Lierne",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1739",
			level: "1",
			name: "Raarvihke - Røyrvik",
			shortName: "",
			parentCode: "",
			notes:
				"13. juni 2014 ble det vedtatt at  kommunenavnet skulle være tospråklig (samisk -norsk)",
		},
		{
			code: "1740",
			level: "1",
			name: "Namsskogan",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1742",
			level: "1",
			name: "Grong",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1743",
			level: "1",
			name: "Høylandet",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1744",
			level: "1",
			name: "Overhalla",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1748",
			level: "1",
			name: "Fosnes",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1749",
			level: "1",
			name: "Flatanger",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1750",
			level: "1",
			name: "Vikna",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1751",
			level: "1",
			name: "Nærøy",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1755",
			level: "1",
			name: "Leka",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1756",
			level: "1",
			name: "Inderøy",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1804",
			level: "1",
			name: "Bodø",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1805",
			level: "1",
			name: "Narvik",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1811",
			level: "1",
			name: "Bindal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1812",
			level: "1",
			name: "Sømna",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1813",
			level: "1",
			name: "Brønnøy",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1815",
			level: "1",
			name: "Vega",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1816",
			level: "1",
			name: "Vevelstad",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1818",
			level: "1",
			name: "Herøy",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1820",
			level: "1",
			name: "Alstahaug",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1822",
			level: "1",
			name: "Leirfjord",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1824",
			level: "1",
			name: "Vefsn",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1825",
			level: "1",
			name: "Grane",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1826",
			level: "1",
			name: "Hattfjelldal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1827",
			level: "1",
			name: "Dønna",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1828",
			level: "1",
			name: "Nesna",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1832",
			level: "1",
			name: "Hemnes",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1833",
			level: "1",
			name: "Rana",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1834",
			level: "1",
			name: "Lurøy",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1835",
			level: "1",
			name: "Træna",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1836",
			level: "1",
			name: "Rødøy",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1837",
			level: "1",
			name: "Meløy",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1838",
			level: "1",
			name: "Gildeskål",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1839",
			level: "1",
			name: "Beiarn",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1840",
			level: "1",
			name: "Saltdal",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1841",
			level: "1",
			name: "Fauske",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1845",
			level: "1",
			name: "Sørfold",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1848",
			level: "1",
			name: "Steigen",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1849",
			level: "1",
			name: "Hamarøy - Hábmer",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1850",
			level: "1",
			name: "Divtasvuodna - Tysfjord",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1851",
			level: "1",
			name: "Lødingen",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1852",
			level: "1",
			name: "Tjeldsund",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1853",
			level: "1",
			name: "Evenes",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1854",
			level: "1",
			name: "Ballangen",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1856",
			level: "1",
			name: "Røst",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1857",
			level: "1",
			name: "Værøy",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1859",
			level: "1",
			name: "Flakstad",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1860",
			level: "1",
			name: "Vestvågøy",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1865",
			level: "1",
			name: "Vågan",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1866",
			level: "1",
			name: "Hadsel",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1867",
			level: "1",
			name: "Bø",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1868",
			level: "1",
			name: "Øksnes",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1870",
			level: "1",
			name: "Sortland",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1871",
			level: "1",
			name: "Andøy",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1874",
			level: "1",
			name: "Moskenes",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1902",
			level: "1",
			name: "Tromsø",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1903",
			level: "1",
			name: "Harstad",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1911",
			level: "1",
			name: "Kvæfjord",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1913",
			level: "1",
			name: "Skånland",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1917",
			level: "1",
			name: "Ibestad",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1919",
			level: "1",
			name: "Gratangen",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1920",
			level: "1",
			name: "Loabák - Lavangen",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1922",
			level: "1",
			name: "Bardu",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1923",
			level: "1",
			name: "Salangen",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1924",
			level: "1",
			name: "Målselv",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1925",
			level: "1",
			name: "Sørreisa",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1926",
			level: "1",
			name: "Dyrøy",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1927",
			level: "1",
			name: "Tranøy",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1928",
			level: "1",
			name: "Torsken",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1929",
			level: "1",
			name: "Berg",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1931",
			level: "1",
			name: "Lenvik",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1933",
			level: "1",
			name: "Balsfjord",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1936",
			level: "1",
			name: "Karlsøy",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1938",
			level: "1",
			name: "Lyngen",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1939",
			level: "1",
			name: "Storfjord - Omasvuotna - Omasvuono",
			shortName: "",
			parentCode: "",
			notes:
				"7. mars 2014 ble det vedtatt at kommunenavnet skulle være trespråklig (norsk - samisk - kvensk)",
		},
		{
			code: "1940",
			level: "1",
			name: "Gáivuotna - Kåfjord",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1941",
			level: "1",
			name: "Skjervøy",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1942",
			level: "1",
			name: "Nordreisa",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "1943",
			level: "1",
			name: "Kvænangen",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "2002",
			level: "1",
			name: "Vardø",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "2003",
			level: "1",
			name: "Vadsø",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "2004",
			level: "1",
			name: "Hammerfest",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "2011",
			level: "1",
			name: "Guovdageaidnu - Kautokeino",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "2012",
			level: "1",
			name: "Alta",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "2014",
			level: "1",
			name: "Loppa",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "2015",
			level: "1",
			name: "Hasvik",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "2017",
			level: "1",
			name: "Kvalsund",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "2018",
			level: "1",
			name: "Måsøy",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "2019",
			level: "1",
			name: "Nordkapp",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "2020",
			level: "1",
			name: "Porsanger - Porsángu - Porsanki",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "2021",
			level: "1",
			name: "Kárásjohka - Karasjok",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "2022",
			level: "1",
			name: "Lebesby",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "2023",
			level: "1",
			name: "Gamvik",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "2024",
			level: "1",
			name: "Berlevåg",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "2025",
			level: "1",
			name: "Deatnu Tana",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "2027",
			level: "1",
			name: "Unjárga - Nesseby",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "2028",
			level: "1",
			name: "Båtsfjord",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "2030",
			level: "1",
			name: "Sør-Varanger",
			shortName: "",
			parentCode: "",
			notes: "",
		},
		{
			code: "9999",
			level: "1",
			name: "Uoppgitt",
			shortName: "",
			parentCode: "",
			notes: "",
		},
	],
	_links: {
		self: {
			href: "/versions/943",
		},
	},
};
