module.exports = {
	name: "Gruppering av familier 2006",
	validFrom: "2006-01-01",
	validTo: "2008-01-01",
	introduction: "Description",
	user: "Ziggy Stardust",
	owningSection: "714",
	legalBase: "",
	publications: "",
	derivedFrom: "",
	published: ["Bokmål"],
	levels: [
		{
			levelNumber: 1,
			levelName: "Nivå 1",
		},
		{
			levelNumber: 2,
			levelName: "Nivå 2",
		},
		{
			levelNumber: 3,
			levelName: "Nivå 3",
		},
	],
	correspondenceTables: [],
	classificationVariants: [
		{
			name: "Variant - Tilleggsinndeling for familier",
			_links: {
				self: {
					href: "http://al-klass-app-u1.ssb.no:8080/variants/12",
				},
			},
		},
	],
	classificationItems: [
		{
			code: "1",
			level: "1",
			name: "Enpersonfamilie",
			shortName: "",
			notes: "",
			parentCode: "",
		},
		{
			code: "1.1",
			level: "2",
			name: "Enpersonfamilie",
			shortName: "",
			notes: "",
			parentCode: "1",
		},
		{
			code: "1.1.1",
			level: "3",
			name: "Enpersonfamilie, person under 30 år",
			shortName: "",
			notes: "",
			parentCode: "1.1",
		},
		{
			code: "1.1.2",
			level: "3",
			name: "Enpersonfamilie, person 30-44 år",
			shortName: "",
			notes: "",
			parentCode: "1.1",
		},
		{
			code: "1.1.3",
			level: "3",
			name: "Enpersonfamilie, person 45-66 år",
			shortName: "",
			notes: "",
			parentCode: "1.1",
		},
		{
			code: "1.1.4",
			level: "1",
			name: "Enpersonfamilie, person 67 år og over",
			shortName: "",
			notes: "",
			parentCode: "1.1",
		},
		{
			code: "2",
			level: "1",
			name: "Familier med barn (yngste barn 0-17 år)",
			shortName: "",
			notes: "",
			parentCode: "",
		},
		{
			code: "2.1",
			level: "2",
			name: "Par med små barn (yngste barn 0-5 år)",
			shortName: "",
			notes: "",
			parentCode: "2",
		},
		{
			code: "2.1.1",
			level: "3",
			name: "Ektepar med små barn (yngste barn 0-5 år)",
			shortName: "",
			notes: "",
			parentCode: "2.1",
		},
		{
			code: "2.1.2",
			level: "3",
			name: "Samboerpar med små barn (yngste barn 0-5 år)",
			shortName: "",
			notes: "",
			parentCode: "2.1",
		},
		{
			code: "2.2",
			level: "2",
			name: "Par med store barn (yngste barn 6-17 år)",
			shortName: "",
			notes: "",
			parentCode: "2",
		},
		{
			code: "2.2.1",
			level: "3",
			name: "Ektepar med store barn (yngste barn 6-17 år)",
			shortName: "",
			notes: "",
			parentCode: "2.2",
		},
		{
			code: "2.2.2",
			level: "1",
			name: "Samboerpar med store barn (yngste barn 6-17 år)",
			shortName: "",
			notes: "",
			parentCode: "",
		},
		{
			code: "2.3",
			level: "1",
			name: "Mor/far med små barn (yngste barn 0-5 år)",
			shortName: "",
			notes: "",
			parentCode: "",
		},
		{
			code: "2.3.1",
			level: "1",
			name: "Mor med små barn (yngste barn 0-5 år)",
			shortName: "",
			notes: "",
			parentCode: "",
		},
		{
			code: "2.3.2",
			level: "1",
			name: "Far med små barn (yngste barn 0-5 år)",
			shortName: "",
			notes: "",
			parentCode: "",
		},
		{
			code: "2.4",
			level: "1",
			name: "Mor/far med store barn (yngste barn 6-17 år)",
			shortName: "",
			notes: "",
			parentCode: "",
		},
		{
			code: "2.4.1",
			level: "1",
			name: "Mor med store barn (yngste barn 6-17 år)",
			shortName: "",
			notes: "",
			parentCode: "",
		},
		{
			code: "2.4.2",
			level: "1",
			name: "Far med store barn (yngste barn 6-17 år)",
			shortName: "",
			notes: "",
			parentCode: "",
		},
		{
			code: "3",
			level: "1",
			name: "Andre familier",
			shortName: "",
			notes: "",
			parentCode: "",
		},
		{
			code: "3.1",
			level: "1",
			name: "Par uten barn",
			shortName: "",
			notes: "",
			parentCode: "",
		},
		{
			code: "3.1.1",
			level: "1",
			name: "Ektepar uten barn, eldste person under 30 år",
			shortName: "",
			notes: "",
			parentCode: "",
		},
		{
			code: "3.1.2",
			level: "1",
			name: "Ektepar uten barn, eldste person 30-44 år",
			shortName: "",
			notes: "",
			parentCode: "",
		},
		{
			code: "3.1.3",
			level: "1",
			name: "Ektepar uten barn, eldste person 45-66 år",
			shortName: "",
			notes: "",
			parentCode: "",
		},
		{
			code: "3.1.4",
			level: "1",
			name: "Ektepar uten barn, eldste person 67 år og over",
			shortName: "",
			notes: "",
			parentCode: "",
		},
		{
			code: "3.1.5",
			level: "1",
			name: "Samboerpar uten barn, eldste person under 30 år",
			shortName: "",
			notes: "",
			parentCode: "",
		},
		{
			code: "3.1.6",
			level: "1",
			name: "Samboerpar uten barn, eldste person 30-44 år",
			shortName: "",
			notes: "",
			parentCode: "",
		},
		{
			code: "3.1.7",
			level: "1",
			name: "Samboerpar uten barn, eldste person 45-66 år",
			shortName: "",
			notes: "",
			parentCode: "",
		},
		{
			code: "3.1.8",
			level: "1",
			name: "Samboerpar uten barn, eldste person 67 år og over",
			shortName: "",
			notes: "",
			parentCode: "",
		},
		{
			code: "3.2",
			level: "1",
			name: "Par med voksne barn (yngste barn 18 år og over)",
			shortName: "",
			notes: "",
			parentCode: "",
		},
		{
			code: "3.2.1",
			level: "1",
			name: "Ektepar med voksne barn (yngste barn 18 år og over)",
			shortName: "",
			notes: "",
			parentCode: "",
		},
		{
			code: "3.2.2",
			level: "1",
			name: "Samboerpar med voksne barn (yngste barn 18 år og over)",
			shortName: "",
			notes: "",
			parentCode: "",
		},
		{
			code: "3.3",
			level: "1",
			name: "Mor/far med voksne barn (yngste barn 18 år og over)",
			shortName: "",
			notes: "",
			parentCode: "",
		},
		{
			code: "3.3.1",
			level: "1",
			name: "Mor med voksne barn (yngste barn 18 år og over)",
			shortName: "",
			notes: "",
			parentCode: "",
		},
		{
			code: "3.3.2",
			level: "1",
			name: "Far med voksne barn (yngste barn 18 år og over)",
			shortName: "",
			notes: "",
			parentCode: "",
		},
		{
			code: "3.4",
			level: "1",
			name: "Andre familier",
			shortName: "",
			notes: "",
			parentCode: "",
		},
		{
			code: "3.4.1",
			level: "1",
			name: "Andre familier",
			shortName: "",
			notes: "",
			parentCode: "",
		},
	],
	_links: {
		self: {
			href: "http://al-klass-app-u1.ssb.no:8080/versions/11",
		},
	},
};
