module.exports = {
	codeChanges: [
		{
			oldCode: "0101",
			oldName: "Halden",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0104",
			oldName: "Moss",
			oldShortName: "ms",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0105",
			oldName: "Sarpsborg",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0106",
			oldName: "Fredrikstad",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0111",
			oldName: "Hvaler",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0118",
			oldName: "Aremark",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0119",
			oldName: "Marker",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0121",
			oldName: "Rømskog",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0122",
			oldName: "Trøgstad",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0123",
			oldName: "Spydeberg",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0124",
			oldName: "Askim",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0125",
			oldName: "Eidsberg",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0127",
			oldName: "Skiptvet",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0128",
			oldName: "Rakkestad",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0135",
			oldName: "Råde",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0136",
			oldName: "Rygge",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0137",
			oldName: "Våler",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0138",
			oldName: "Hobøl",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0211",
			oldName: "Vestby",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0213",
			oldName: "Ski",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0214",
			oldName: "Ås",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0215",
			oldName: "Frogn",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0216",
			oldName: "Nesodden",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0217",
			oldName: "Oppegård",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0219",
			oldName: "Bærum",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0220",
			oldName: "Asker",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0221",
			oldName: "Aurskog-Høland",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0226",
			oldName: "Sørum",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0227",
			oldName: "Fet",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0228",
			oldName: "Rælingen",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0229",
			oldName: "Enebakk",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0230",
			oldName: "Lørenskog",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0231",
			oldName: "Skedsmo",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0233",
			oldName: "Nittedal",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0234",
			oldName: "Gjerdrum",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0235",
			oldName: "Ullensaker",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0236",
			oldName: "Nes",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0237",
			oldName: "Eidsvoll",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0238",
			oldName: "Nannestad",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0239",
			oldName: "Hurdal",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0301",
			oldName: "Oslo",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0402",
			oldName: "Kongsvinger",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0403",
			oldName: "Hamar",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0412",
			oldName: "Ringsaker",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0415",
			oldName: "Løten",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0417",
			oldName: "Stange",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0418",
			oldName: "Nord-Odal",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0419",
			oldName: "Sør-Odal",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0420",
			oldName: "Eidskog",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0423",
			oldName: "Grue",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0425",
			oldName: "Åsnes",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0426",
			oldName: "Våler",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0427",
			oldName: "Elverum",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0428",
			oldName: "Trysil",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0429",
			oldName: "Åmot",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0430",
			oldName: "Stor-Elvdal",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0432",
			oldName: "Rendalen",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0434",
			oldName: "Engerdal",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0436",
			oldName: "Tolga",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0437",
			oldName: "Tynset",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0438",
			oldName: "Alvdal",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0439",
			oldName: "Folldal",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0441",
			oldName: "Os",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0501",
			oldName: "Lillehammer",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0502",
			oldName: "Gjøvik",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0511",
			oldName: "Dovre",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0511",
			oldName: "Dovre",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0511",
			oldName: "Dovre",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0511",
			oldName: "Dovre",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0511",
			oldName: "Dovre",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0511",
			oldName: "Dovre",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0511",
			oldName: "Dovre",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0511",
			oldName: "Dovre",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0511",
			oldName: "Dovre",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0511",
			oldName: "Dovre",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0511",
			oldName: "Dovre",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0511",
			oldName: "Dovre",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0511",
			oldName: "Dovre",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0511",
			oldName: "Dovre",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0511",
			oldName: "Dovre",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0511",
			oldName: "Dovre",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0511",
			oldName: "Dovre",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0511",
			oldName: "Dovre",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0511",
			oldName: "Dovre",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0511",
			oldName: "Dovre",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0511",
			oldName: "Dovre",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0511",
			oldName: "Dovre",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0511",
			oldName: "Dovre",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0511",
			oldName: "Dovre",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0602",
			oldName: "Drammen",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0604",
			oldName: "Kongsberg",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0605",
			oldName: "Ringerike",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0612",
			oldName: "Hole",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0615",
			oldName: "Flå",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0616",
			oldName: "Nes",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0617",
			oldName: "Gol",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0618",
			oldName: "Hemsedal",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0619",
			oldName: "Ål",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0620",
			oldName: "Hol",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0621",
			oldName: "Sigdal",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0622",
			oldName: "Krødsherad",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0623",
			oldName: "Modum",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0624",
			oldName: "Øvre Eiker",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0625",
			oldName: "Nedre Eiker",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0626",
			oldName: "Lier",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0627",
			oldName: "Røyken",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0628",
			oldName: "Hurum",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0631",
			oldName: "Flesberg",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0632",
			oldName: "Rollag",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0633",
			oldName: "Nore og Uvdal",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0701",
			oldName: "Horten",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0702",
			oldName: "Holmestrand",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0704",
			oldName: "Tønsberg",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0706",
			oldName: "Sandefjord",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0709",
			oldName: "Larvik",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0711",
			oldName: "Svelvik",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0713",
			oldName: "Sande",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0714",
			oldName: "Hof",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0716",
			oldName: "Re",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0719",
			oldName: "Andebu",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0720",
			oldName: "Stokke",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0722",
			oldName: "Nøtterøy",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0723",
			oldName: "Tjøme",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0728",
			oldName: "Lardal",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0805",
			oldName: "Porsgrunn",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0806",
			oldName: "Skien",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0807",
			oldName: "Notodden",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0811",
			oldName: "Siljan",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0814",
			oldName: "Bamble",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0815",
			oldName: "Kragerø",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0817",
			oldName: "Drangedal",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0819",
			oldName: "Nome",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0821",
			oldName: "Bø",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0822",
			oldName: "Sauherad",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0826",
			oldName: "Tinn",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0827",
			oldName: "Hjartdal",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0828",
			oldName: "Seljord",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0829",
			oldName: "Kviteseid",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0830",
			oldName: "Nissedal",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0831",
			oldName: "Fyresdal",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0833",
			oldName: "Tokke",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0834",
			oldName: "Vinje",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0901",
			oldName: "Risør",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0904",
			oldName: "Grimstad",
			oldShortName: "",
			newCode: "0001",
			newName: "MegaOslo",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0906",
			oldName: "Arendal",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0911",
			oldName: "Gjerstad",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0912",
			oldName: "Vegårshei",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0914",
			oldName: "Tvedestrand",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0919",
			oldName: "Froland",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0926",
			oldName: "Lillesand",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0928",
			oldName: "Birkenes",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0929",
			oldName: "Åmli",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0935",
			oldName: "Iveland",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0937",
			oldName: "Evje og Hornnes",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0938",
			oldName: "Bygland",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0940",
			oldName: "Valle",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "0941",
			oldName: "Bykle",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1001",
			oldName: "Kristiansand",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1002",
			oldName: "Mandal",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1003",
			oldName: "Farsund",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1004",
			oldName: "Flekkefjord",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1014",
			oldName: "Vennesla",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1017",
			oldName: "Songdalen",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1018",
			oldName: "Søgne",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1021",
			oldName: "Marnardal",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1026",
			oldName: "Åseral",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1027",
			oldName: "Audnedal",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1029",
			oldName: "Lindesnes",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1032",
			oldName: "Lyngdal",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1034",
			oldName: "Hægebostad",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1037",
			oldName: "Kvinesdal",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1046",
			oldName: "Sirdal",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1101",
			oldName: "Eigersund",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1102",
			oldName: "Sandnes",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1103",
			oldName: "Stavanger",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1106",
			oldName: "Haugesund",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1111",
			oldName: "Sokndal",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1112",
			oldName: "Lund",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1114",
			oldName: "Bjerkreim",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1119",
			oldName: "Hå",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1120",
			oldName: "Klepp",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1121",
			oldName: "Time",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1122",
			oldName: "Gjesdal",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1124",
			oldName: "Sola",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1127",
			oldName: "Randaberg",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1129",
			oldName: "Forsand",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1130",
			oldName: "Strand",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1133",
			oldName: "Hjelmeland",
			oldShortName: "",
			newCode: "0004",
			newName: "BigOilStavanger",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1134",
			oldName: "Suldal",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1135",
			oldName: "Sauda",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1141",
			oldName: "Finnøy",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1142",
			oldName: "Rennesøy",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1144",
			oldName: "Kvitsøy",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1145",
			oldName: "Bokn",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1146",
			oldName: "Tysvær",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1149",
			oldName: "Karmøy",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1151",
			oldName: "Utsira",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1160",
			oldName: "Vindafjord",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1201",
			oldName: "Bergen",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1211",
			oldName: "Etne",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1216",
			oldName: "Sveio",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1219",
			oldName: "Bømlo",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1221",
			oldName: "Stord",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1222",
			oldName: "Fitjar",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1223",
			oldName: "Tysnes",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1224",
			oldName: "Kvinnherad",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1227",
			oldName: "Jondal",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1228",
			oldName: "Odda",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1231",
			oldName: "Ullensvang",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1232",
			oldName: "Eidfjord",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1233",
			oldName: "Ulvik",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1234",
			oldName: "Granvin",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1235",
			oldName: "Voss",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1238",
			oldName: "Kvam",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1241",
			oldName: "Fusa",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1242",
			oldName: "Samnanger",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1243",
			oldName: "Os",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1244",
			oldName: "Austevoll",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1245",
			oldName: "Sund",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1246",
			oldName: "Fjell",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1247",
			oldName: "Askøy",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1251",
			oldName: "Vaksdal",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1252",
			oldName: "Modalen",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1253",
			oldName: "Osterøy",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1256",
			oldName: "Meland",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1259",
			oldName: "Øygarden",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1260",
			oldName: "Radøy",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1263",
			oldName: "Lindås",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1264",
			oldName: "Austrheim",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1265",
			oldName: "Fedje",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1266",
			oldName: "Masfjorden",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1401",
			oldName: "Flora",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1411",
			oldName: "Gulen",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1412",
			oldName: "Solund",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1413",
			oldName: "Hyllestad",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1416",
			oldName: "Høyanger",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1417",
			oldName: "Vik",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1418",
			oldName: "Balestrand",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1419",
			oldName: "Leikanger",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1420",
			oldName: "Sogndal",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1421",
			oldName: "Aurland",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1422",
			oldName: "Lærdal",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1424",
			oldName: "Årdal",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1426",
			oldName: "Luster",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1428",
			oldName: "Askvoll",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1429",
			oldName: "Fjaler",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1430",
			oldName: "Gaular",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1431",
			oldName: "Jølster",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1432",
			oldName: "Førde",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1433",
			oldName: "Naustdal",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1438",
			oldName: "Bremanger",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1439",
			oldName: "Vågsøy",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1441",
			oldName: "Selje",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1443",
			oldName: "Eid",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1444",
			oldName: "Hornindal",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1445",
			oldName: "Gloppen",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1449",
			oldName: "Stryn",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1502",
			oldName: "Molde",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1504",
			oldName: "Ålesund",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1505",
			oldName: "Kristiansund",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1511",
			oldName: "Vanylven",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1514",
			oldName: "Sande",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1515",
			oldName: "Herøy",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1516",
			oldName: "Ulstein",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1517",
			oldName: "Hareid",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1519",
			oldName: "Volda",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1520",
			oldName: "Ørsta",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1523",
			oldName: "Ørskog",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1524",
			oldName: "Norddal",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1525",
			oldName: "Stranda",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1526",
			oldName: "Stordal",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1528",
			oldName: "Sykkylven",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1529",
			oldName: "Skodje",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1531",
			oldName: "Sula",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1532",
			oldName: "Giske",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1534",
			oldName: "Haram",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1535",
			oldName: "Vestnes",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1539",
			oldName: "Rauma",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1543",
			oldName: "Nesset",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1545",
			oldName: "Midsund",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1546",
			oldName: "Sandøy",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1547",
			oldName: "Aukra",
			oldShortName: "",
			newCode: "0002",
			newName: "KjempeBergen",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1548",
			oldName: "Fræna",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1551",
			oldName: "Eide",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1554",
			oldName: "Averøy",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1557",
			oldName: "Gjemnes",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1560",
			oldName: "Tingvoll",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1563",
			oldName: "Sunndal",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1566",
			oldName: "Surnadal",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1567",
			oldName: "Rindal",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1571",
			oldName: "Halsa",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1573",
			oldName: "Smøla",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1576",
			oldName: "Aure",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1601",
			oldName: "Trondheim",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1612",
			oldName: "Hemne",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1613",
			oldName: "Snillfjord",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1617",
			oldName: "Hitra",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1620",
			oldName: "Frøya",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1621",
			oldName: "Ørland",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1622",
			oldName: "Agdenes",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1624",
			oldName: "Rissa",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1627",
			oldName: "Bjugn",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1630",
			oldName: "Åfjord",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1632",
			oldName: "Roan",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1633",
			oldName: "Osen",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1634",
			oldName: "Oppdal",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1635",
			oldName: "Rennebu",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1636",
			oldName: "Meldal",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1638",
			oldName: "Orkdal",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1640",
			oldName: "Røros",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1644",
			oldName: "Holtålen",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1648",
			oldName: "Midtre Gauldal",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1653",
			oldName: "Melhus",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1657",
			oldName: "Skaun",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1662",
			oldName: "Klæbu",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1663",
			oldName: "Malvik",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1664",
			oldName: "Selbu",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1665",
			oldName: "Tydal",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1702",
			oldName: "Steinkjer",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1703",
			oldName: "Namsos",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1711",
			oldName: "Meråker",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1714",
			oldName: "Stjørdal",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1717",
			oldName: "Frosta",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1718",
			oldName: "Leksvik",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1719",
			oldName: "Levanger",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1721",
			oldName: "Verdal",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1724",
			oldName: "Verran",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1725",
			oldName: "Namdalseid",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1736",
			oldName: "Snåase Snåsa",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1738",
			oldName: "Lierne",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1739",
			oldName: "Raarvihke Røyrvik ",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1740",
			oldName: "Namsskogan",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1742",
			oldName: "Grong",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1743",
			oldName: "Høylandet",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1744",
			oldName: "Overhalla",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1748",
			oldName: "Fosnes",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1749",
			oldName: "Flatanger",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1750",
			oldName: "Vikna",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1751",
			oldName: "Nærøy",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1755",
			oldName: "Leka",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1756",
			oldName: "Inderøy",
			oldShortName: "",
			newCode: "0003",
			newName: "StorTrondheim",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1804",
			oldName: "Bodø",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1805",
			oldName: "Narvik",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1811",
			oldName: "Bindal",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1812",
			oldName: "Sømna",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1813",
			oldName: "Brønnøy",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1815",
			oldName: "Vega",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1816",
			oldName: "Vevelstad",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1818",
			oldName: "Herøy",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1820",
			oldName: "Alstahaug",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1822",
			oldName: "Leirfjord",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1824",
			oldName: "Vefsn",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1825",
			oldName: "Grane",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1826",
			oldName: "Hattfjelldal",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1827",
			oldName: "Dønna",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1828",
			oldName: "Nesna",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1832",
			oldName: "Hemnes",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1833",
			oldName: "Rana",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1834",
			oldName: "Lurøy",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1835",
			oldName: "Træna",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1836",
			oldName: "Rødøy",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1837",
			oldName: "Meløy",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1838",
			oldName: "Gildeskål",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1839",
			oldName: "Beiarn",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1840",
			oldName: "Saltdal",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1841",
			oldName: "Fauske",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1845",
			oldName: "Sørfold",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1848",
			oldName: "Steigen",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1849",
			oldName: "Hábmer Hamarøy",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1850",
			oldName: "Divtasvuodna Tysfjord",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1851",
			oldName: "Lødingen",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1852",
			oldName: "Tjeldsund",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1853",
			oldName: "Evenes",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1854",
			oldName: "Ballangen",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1856",
			oldName: "Røst",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1857",
			oldName: "Værøy",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1859",
			oldName: "Flakstad",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1860",
			oldName: "Vestvågøy",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1865",
			oldName: "Vågan",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1866",
			oldName: "Hadsel",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1867",
			oldName: "Bø",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1868",
			oldName: "Øksnes",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1870",
			oldName: "Sortland",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1871",
			oldName: "Andøy",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1874",
			oldName: "Moskenes",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1902",
			oldName: "Tromsø",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1903",
			oldName: "Harstad",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1911",
			oldName: "Kvæfjord",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1913",
			oldName: "Skånland",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1917",
			oldName: "Ibestad",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1919",
			oldName: "Gratangen",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1920",
			oldName: "Lavangen",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1922",
			oldName: "Bardu",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1923",
			oldName: "Salangen",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1924",
			oldName: "Målselv",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1925",
			oldName: "Sørreisa",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1926",
			oldName: "Dyrøy",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1927",
			oldName: "Tranøy",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1928",
			oldName: "Torsken",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1929",
			oldName: "Berg",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1931",
			oldName: "Lenvik",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1933",
			oldName: "Balsfjord",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1936",
			oldName: "Karlsøy",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1938",
			oldName: "Lyngen",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1939",
			oldName: "Omasvuotna Storfjord Omasvuonon ",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1940",
			oldName: "Gáivuotna Kåfjord",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1941",
			oldName: "Skjervøy",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1942",
			oldName: "Nordreisa",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "1943",
			oldName: "Kvænangen",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "2002",
			oldName: "Vardø",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "2003",
			oldName: "Vadsø",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "2004",
			oldName: "Hammerfest",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "2011",
			oldName: "Guovdageaidnu Kautokeino",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "2012",
			oldName: "Alta",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "2014",
			oldName: "Loppa",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "2015",
			oldName: "Hasvik",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "2017",
			oldName: "Kvalsund",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "2018",
			oldName: "Måsøy",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "2019",
			oldName: "Nordkapp",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "2020",
			oldName: "Porsanger Porsángu Porsanki",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "2021",
			oldName: "Kárásjohka Karasjok",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "2022",
			oldName: "Lebesby",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "2023",
			oldName: "Gamvik",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "2024",
			oldName: "Berlevåg",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "2025",
			oldName: "Deatnu Tana",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "2027",
			oldName: "Unjárga Nesseby",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "2028",
			oldName: "Båtsfjord",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "2030",
			oldName: "Sør-Varanger",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
		{
			oldCode: "9999",
			oldName: "Uoppgitt",
			oldShortName: "",
			newCode: "0005",
			newName: "NorthTromsø",
			newShortName: "",
			changeOccurred: "2026-01-01",
		},
	],
};
