# Deploy config for the test cluster
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: klass-web
  namespace: dapla-metadata

spec:

  ingresses:
    - https://klass-web.test.ssb.no
  image: "{{ image }}"  # Injected from the GitHub Action

  port: 8080
  ttl: 3h
  replicas:
    max: 1
    min: 1
  resources:
    requests:
      cpu: 50m
      memory: 32Mi