module.exports = {
	name: "Store og små kommuner",
	validFrom: "2014-01-01",
	validTo: "2015-12-01",
	introduction: "Ønsker å vise store og små kommuner",
	contactPerson: "Klass Administrator",
	owningSection: "133",
	published: [],
	correspondenceTables: [],
	changelogs: [],
	levels: [
		{
			levelNumber: 1,
			levelName: "Nivå 1",
		},
		{
			levelNumber: 2,
			levelName: "Nivå 2",
		},
	],
	classificationItems: [
		{
			code: "1",
			level: "1",
			name: "Store kommuner",
			shortName: "",
			notes: "",
			parentCode: "",
		},
		{
			code: "2",
			level: "1",
			name: "Små kommuner",
			shortName: "",
			notes: "",
			parentCode: "",
		},
		{
			code: "1102",
			level: "2",
			name: "Sandnes",
			shortName: "",
			notes: "",
			parentCode: "1",
		},
		{
			code: "1103",
			level: "2",
			name: "Stavanger",
			shortName: "",
			notes: "",
			parentCode: "1",
		},
		{
			code: "1111",
			level: "2",
			name: "Sokndal",
			shortName: "",
			notes: "",
			parentCode: "2",
		},
		{
			code: "1112",
			level: "2",
			name: "Lund",
			shortName: "",
			notes: "",
			parentCode: "2",
		},
	],
	_links: {
		self: {
			href: "http://al-klass-app-u1.ssb.no:8080/rest/v1/variants/467",
		},
	},
};
