name: Deploy alerts
run-name: Deploy alerts for klass-web to test and prod

on:
  push:
    branches:
      - master
    paths:
      - ".nais/prod/alerts.yaml"
      - ".nais/test/alerts.yaml"
      - ".github/workflows/alert-deploy.yml"
permissions:
  id-token: write

jobs:
  test-deploy:
    name: Deploy alerts to test
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Deploy to test
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: test
          RESOURCE: .nais/test/alerts.yaml
          DEPLOY_SERVER: deploy.ssb.cloud.nais.io:443

  prod-deploy:
    name: Deploy alerts to prod
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Deploy to test
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: prod
          RESOURCE: .nais/prod/alerts.yaml
          DEPLOY_SERVER: deploy.ssb.cloud.nais.io:443
