name: Build and deploy to nais

on:
  release:
    types: [ published ]
  push:
    branches:
      - main

env:
  REGISTRY: europe-north1-docker.pkg.dev/artifact-registry-5n/dapla-metadata-docker/klass-web
  IMAGE: klass-web
  TAG: ${{ github.head_ref }}-${{ github.sha }}

jobs:
  docker-build:
    name: Docker build
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.metadata.outputs.tags }}
      config-path: ${{ steps.nais-deploy-vars.outputs.nais_config_path }}
      cluster: ${{ steps.nais-deploy-vars.outputs.cluster }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Authenticate to Google Cloud"
        id: "auth"
        uses: "google-github-actions/auth@v2.1.7"
        with:
          workload_identity_provider: "projects/848539402404/locations/global/workloadIdentityPools/gh-actions/providers/gh-actions"
          service_account: "gh-actions-dapla-metadata@artifact-registry-5n.iam.gserviceaccount.com"
          token_format: "access_token"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"

      - name: Docker meta
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE }}
          # Docker tags based on the following events/attributes
          tags: |
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          push: true
          tags: |
            ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}

      - name: Output image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Generate NAIS deploy variables
        id: nais-deploy-vars
        run: |
          if [[ ${{ github.event_name }} == "release" ]]; then
            echo "cluster=prod" >> "$GITHUB_OUTPUT"
            echo "nais_config_path=.nais/prod/nais.yaml" >> "$GITHUB_OUTPUT"
          else
            echo "cluster=test" >> "$GITHUB_OUTPUT"
            echo "nais_config_path=.nais/test/nais.yaml" >> "$GITHUB_OUTPUT"
          fi 


  deploy:
    name: Deploy to NAIS
    runs-on: ubuntu-latest
    needs: docker-build
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ needs.docker-build.outputs.cluster }}
          RESOURCE: ${{ needs.docker-build.outputs.config-path }}
          VAR: image=${{ needs.docker-build.outputs.image-tag }}
          DEPLOY_SERVER: deploy.ssb.cloud.nais.io:443